version: "3"
services:
  db-data:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - data_volumes:/var/lib/postgresql

volumes:
  data_volumes: